# Загружаем библиотеки
library(quantmod)
library(writexl)
library(rusquant)

# Создаем список тикеров для российских компаний
tickers <- c("IMOEX",
             "SBER",
             "LKOH",
             "TCSG",
             "GAZP",
             "GMKN",
             "NLMK",
             "VTBR",
             "CHMF",
             "YDEX",
             "MTLR",
             "ALRS",
             "AFLT",
             "TATN",
             "PLZL",
             "MAGN",
             "ROSN",
             "UWGN",
             "EUTR",
             "TRNFP",
             "IRKT",
             "NVTK",
             "OZON",
             "SNGSP",
             "SBERP",
             "SFIN",
             "QIWI",
             "POSI",
             "SNGS",
             "MOEX",
             "MGNT",
             "SGZH",
             "HEAD",
             "FLOT",
             "AFKS",
             "OZPH",
             "SOFL",
             "SIBN",
             "UGLD",
             "MTLRP",
             "RNFT",
             "TATNP",
             "SMLT",
             "MTSS",
             "SPBE",
             "TRMK",
             "VKCO",
             "PIKK",
             "WUSH",
             "GLTR",
             "RUAL",
             "GTRK",
             "IRAO",
             "RTKM",
             "BSPB",
             "SVCB",
             "UNAC",
             "HYDR",
             "AMEZ",
             "PHOR",
             "ASTR",
             "FESH",
             "LSRG",
             "SVAV",
             "MBNK",
             "ABIO",
             "RASP",
             "MSTT",
             "CBOM",
             "MVID",
             "FEES",
             "MDMG",
             "DATA",
             "SELG",
             "LEAS",
             "BANEP",
             "AGRO",
             "NMTP",
             "BANE",
             "VSEH",
             "RTKMP",
             "DIAS",
             "AQUA",
             "AVAN",
             "ENPG",
             "UPRO",
             "RENI",
             "DSKY",
             "ROLO",
             "BELU",
             "APTK",
             "AKRN",
             "TGKN",
             "GEMC",
             "KMAZ",
             "BLNG",
             "MSNG",
             "LENT",
             "HNFG",
             "LSNGP",
             "OGKB",
             "FIXP",
             "MRKY",
             "DELI",
             "VSMO",
             "LIFE",
             "ELFV",
             "TGKA",
             "ELMT",
             "GCHE",
             "MRKU",
             "PRMD",
             "CIAN",
             "GECO",
             "BSPBP",
             "KAZT",
             "MRKP",
             "ZAYM",
             "GEMA",
             "NKNCP",
             "NSVZ",
             "LSNG",
             "KROT",
             "RBCM",
             "NKHP",
             "LPSB",
             "IVAT",
             "ETLN",
             "VRSB",
             "MRKZ",
             "MRKS",
             "TUZA",
             "PMSBP",
             "CARM",
             "TGKB",
             "MRKC",
             "TGKBP",
             "ROSB",
             "RTGZ",
             "ABRD",
             "UKUZ",
             "MRKV",
             "PRFN",
             "MSRS",
             "UNKL",
             "OMZZP",
             "CNTLP",
             "RZSB",
             "KZOS",
             "KLVZ",
             "MGKL",
             "CNTL",
             "OKEY",
             "KZOSP",
             "KAZTP",
             "NKSH",
             "LNZL",
             "NKNC",
             "UTAR",
             "SVETP",
             "YAKG",
             "KLSB",
             "STSBP",
             "MGTSP",
             "LNZLP",
             "RKKE",
             "BRZL",
             "DVEC",
             "CHMK",
             "KRKNP",
             "KUBE",
             "PMSB",
             "YRSB",
             "SVET",
             "RDRB",
             "CHKZ",
             "YKEN",
             "NAUK",
             "ZVEZ",
             "NNSB",
             "ARSA",
             "JNOSP",
             "CHGZ",
             "MRKK",
             "RGSS",
             "INGR",
             "TTLK",
             "WTCM",
             "KCHE",
             "STSB",
             "RTSBP",
             "SLEN",
             "VEON-RX",
             "MAGE",
             "KOGK",
             "USBN",
             "HIMCP",
             "MAGEP",
             "ASSB",
             "KRSBP",
             "TNSE",
             "RUSI",
             "WTCMP",
             "KUZB",
             "NFAZ",
             "VRSBP",
             "JNOS",
             "KROTP",
             "DIOD",
             "RTSB",
             "KCHEP",
             "EELT",
             "ROST",
             "MISBP",
             "KMEZ",
             "IGSTP",
             "MISB",
             "MGTS",
             "VLHZ",
             "IGST",
             "GAZA",
             "KBSB",
             "BISVP",
             "VSYDP",
             "DZRDP",
             "LVHK",
             "ZILL",
             "SARE",
             "VJGZP",
             "DZRD",
             "YKENP",
             "VGSB",
             "TASB",
             "KRSB",
             "GAZAP",
             "VJGZ",
             "URKZ",
             "SAGO",
             "VSYD",
             "VGSBP",
             "KRKN",
             "KGKCP",
             "KRKOP",
             "PRMB",
             "APRI",
             "KGKC",
             "MFGSP",
             "YRSBP",
             "PAZA",
             "SAGOP",
             "TASBP",
             "SAREP",
             "MRSB",
             "TORSP",
             "TORS",
             "NNSBP",
             "MFGS",
             "ACKO",
             "FIVE",
             "GAZC",
             "GAZS",
             "GAZT",
             "MGNZ")


# Дата начала и окончания
start_date <- as.Date("2017-10-20")
end_date <- as.Date("2019-10-25")

# Создаем датафрейм для хранения цен закрытия
closing_prices <- data.frame(Date = as.Date(character()), stringsAsFactors = FALSE)

# Загружаем данные для каждого тикера
for (ticker in tickers) {
  cat("Загружаем данные для: ", ticker, "\n")
  tryCatch({
    # Загружаем данные с MOEX
    stock <- getSymbols.Moex(ticker, from = start_date, to = end_date)
    
    # Получаем цены закрытия
    close_prices <- (stock$close)
    
    
    # Создаем датафрейм с ценами закрытия
    temp_df <- data.frame(Date = as.Date(stock$timestamp), Close = as.numeric(close_prices))
    names(temp_df)[2] <- ticker  # Переименовываем колонку с ценой
    
    # Объединяем данные по дате
    closing_prices <- merge(closing_prices, temp_df, by = "Date", all = TRUE)
  }, error = function(e) {
    cat("Не удалось загрузить данные для: ", ticker, "\n")
  })
}

# Сохраняем данные в Excel
write_xlsx(closing_prices, "closing_prices_MOEX_today_2017_2019.xlsx")
